# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sinatra-authentication}
  s.version = "0.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Max Justus Spransy"]
  s.date = %q{2009-11-02}
  s.description = %q{Simple authentication plugin for sinatra.}
  s.email = %q{maxjustus@gmail.com}
  s.files = [
    ".gitignore",
     "History.txt",
     "Manifest",
     "Rakefile",
     "TODO",
     "lib/models/abstract_user.rb",
     "lib/models/datamapper_user.rb",
     "lib/models/dm_adapter.rb",
     "lib/models/rufus_tokyo_user.rb",
     "lib/models/tc_adapter.rb",
     "lib/sinatra-authentication.rb",
     "lib/views/edit.haml",
     "lib/views/index.haml",
     "lib/views/login.haml",
     "lib/views/show.haml",
     "lib/views/signup.haml",
     "readme.markdown",
     "sinatra-authentication.gemspec",
     "test/datamapper_test.rb",
     "test/lib/dm_app.rb",
     "test/lib/helper.rb",
     "test/lib/tc_app.rb",
     "test/route_tests.rb",
     "test/rufus_tokyo_test.rb"
  ]
  s.homepage = %q{http://github.com/maxjustus/sinatra-authentication}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Simple authentication plugin for sinatra.}
  s.test_files = [
    "test/lib/tc_app.rb",
     "test/lib/helper.rb",
     "test/lib/dm_app.rb",
     "test/datamapper_test.rb",
     "test/rufus_tokyo_test.rb",
     "test/route_tests.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sinatra>, [">= 0"])
      s.add_runtime_dependency(%q<dm-core>, [">= 0"])
      s.add_runtime_dependency(%q<dm-timestamgemspecs>, [">= 0"])
      s.add_runtime_dependency(%q<dm-validations>, [">= 0"])
      s.add_runtime_dependency(%q<rufus-tokyo>, [">= 0"])
    else
      s.add_dependency(%q<sinatra>, [">= 0"])
      s.add_dependency(%q<dm-core>, [">= 0"])
      s.add_dependency(%q<dm-timestamgemspecs>, [">= 0"])
      s.add_dependency(%q<dm-validations>, [">= 0"])
      s.add_dependency(%q<rufus-tokyo>, [">= 0"])
    end
  else
    s.add_dependency(%q<sinatra>, [">= 0"])
    s.add_dependency(%q<dm-core>, [">= 0"])
    s.add_dependency(%q<dm-timestamgemspecs>, [">= 0"])
    s.add_dependency(%q<dm-validations>, [">= 0"])
    s.add_dependency(%q<rufus-tokyo>, [">= 0"])
  end
end

